# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='broker.proto',
  package='messages',
  syntax='proto3',
  serialized_options=_b('\n-br.com.blk.marketdata.apigrpc.protos.messagesZ-blk.com.br/marketdata/apigrpc/protos/messages\252\002&Blk.MarketData.APIgRPC.Protos.Messages'),
  serialized_pb=_b('\n\x0c\x62roker.proto\x12\x08messages\")\n\x07\x42rokers\x12\x1e\n\x04list\x18\x01 \x03(\x0b\x32\x10.messages.Broker\"6\n\x06\x42roker\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nshort_name\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tB\x87\x01\n-br.com.blk.marketdata.apigrpc.protos.messagesZ-blk.com.br/marketdata/apigrpc/protos/messages\xaa\x02&Blk.MarketData.APIgRPC.Protos.Messagesb\x06proto3')
)




_BROKERS = _descriptor.Descriptor(
  name='Brokers',
  full_name='messages.Brokers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='messages.Brokers.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)


_BROKER = _descriptor.Descriptor(
  name='Broker',
  full_name='messages.Broker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messages.Broker.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='messages.Broker.short_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.Broker.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=123,
)

_BROKERS.fields_by_name['list'].message_type = _BROKER
DESCRIPTOR.message_types_by_name['Brokers'] = _BROKERS
DESCRIPTOR.message_types_by_name['Broker'] = _BROKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Brokers = _reflection.GeneratedProtocolMessageType('Brokers', (_message.Message,), dict(
  DESCRIPTOR = _BROKERS,
  __module__ = 'broker_pb2'
  # @@protoc_insertion_point(class_scope:messages.Brokers)
  ))
_sym_db.RegisterMessage(Brokers)

Broker = _reflection.GeneratedProtocolMessageType('Broker', (_message.Message,), dict(
  DESCRIPTOR = _BROKER,
  __module__ = 'broker_pb2'
  # @@protoc_insertion_point(class_scope:messages.Broker)
  ))
_sym_db.RegisterMessage(Broker)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
