# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2
import broker_pb2 as broker__pb2
import common_pb2 as common__pb2
import login_pb2 as login__pb2
import quote_pb2 as quote__pb2
import security_pb2 as security__pb2
import subscription_pb2 as subscription__pb2
import trades_pb2 as trades__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n$br.com.blk.marketdata.apigrpc.protosZ$blk.com.br/marketdata/apigrpc/protos\252\002\035Blk.MarketData.APIgRPC.Protos'),
  serialized_pb=_b('\n\x0eservices.proto\x1a\nbook.proto\x1a\x0c\x62roker.proto\x1a\x0c\x63ommon.proto\x1a\x0blogin.proto\x1a\x0bquote.proto\x1a\x0esecurity.proto\x1a\x12subscription.proto\x1a\x0ctrades.proto2D\n\x11\x41uthenticationSvc\x12/\n\x05Login\x12\x0f.messages.Login\x1a\x15.messages.AccessToken2\xbc\x02\n\x08\x42ooksSvc\x12\x46\n\x16GetBookByPriceSnapshot\x12\x15.messages.BookRequest\x1a\x15.messages.BookByPrice\x12\x46\n\x16GetBookByOrderSnapshot\x12\x15.messages.BookRequest\x1a\x15.messages.BookByOrder\x12O\n\x14GetBookByOrderStream\x12\x15.messages.BookRequest\x1a\x1e.messages.BookByOrderIncrement0\x01\x12O\n\x14GetBookByPriceStream\x12\x15.messages.BookRequest\x1a\x1e.messages.BookByPriceIncrement0\x01\x32\x97\x01\n\tQuotesSvc\x12\x41\n\x10GetQuoteSnapshot\x12\x1c.messages.SecuritySymbolOrId\x1a\x0f.messages.Quote\x12G\n\x0eGetQuoteStream\x12\x1c.messages.SecuritySymbolOrId\x1a\x15.messages.QuoteUpdate0\x01\x32|\n\x10ReferenceDataSvc\x12\x36\n\rGetSecurities\x12\x0f.messages.Empty\x1a\x14.messages.Securities\x12\x30\n\nGetBrokers\x12\x0f.messages.Empty\x1a\x11.messages.Brokers2Y\n\x0fSubscriptionSvc\x12\x46\n\x15GetSubscriptionStatus\x12\x0f.messages.Empty\x1a\x1c.messages.SubscriptionStatus2\x8a\x01\n\tTradesSvc\x12>\n\x11GetTradesSnapshot\x12\x17.messages.TradesRequest\x1a\x10.messages.Trades\x12=\n\x0fGetTradesStream\x12\x17.messages.TradesRequest\x1a\x0f.messages.Trade0\x01\x42l\n$br.com.blk.marketdata.apigrpc.protosZ$blk.com.br/marketdata/apigrpc/protos\xaa\x02\x1d\x42lk.MarketData.APIgRPC.Protosb\x06proto3')
  ,
  dependencies=[book__pb2.DESCRIPTOR,broker__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,login__pb2.DESCRIPTOR,quote__pb2.DESCRIPTOR,security__pb2.DESCRIPTOR,subscription__pb2.DESCRIPTOR,trades__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_AUTHENTICATIONSVC = _descriptor.ServiceDescriptor(
  name='AuthenticationSvc',
  full_name='AuthenticationSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=134,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='AuthenticationSvc.Login',
    index=0,
    containing_service=None,
    input_type=login__pb2._LOGIN,
    output_type=login__pb2._ACCESSTOKEN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHENTICATIONSVC)

DESCRIPTOR.services_by_name['AuthenticationSvc'] = _AUTHENTICATIONSVC


_BOOKSSVC = _descriptor.ServiceDescriptor(
  name='BooksSvc',
  full_name='BooksSvc',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=205,
  serialized_end=521,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookByPriceSnapshot',
    full_name='BooksSvc.GetBookByPriceSnapshot',
    index=0,
    containing_service=None,
    input_type=book__pb2._BOOKREQUEST,
    output_type=book__pb2._BOOKBYPRICE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookByOrderSnapshot',
    full_name='BooksSvc.GetBookByOrderSnapshot',
    index=1,
    containing_service=None,
    input_type=book__pb2._BOOKREQUEST,
    output_type=book__pb2._BOOKBYORDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookByOrderStream',
    full_name='BooksSvc.GetBookByOrderStream',
    index=2,
    containing_service=None,
    input_type=book__pb2._BOOKREQUEST,
    output_type=book__pb2._BOOKBYORDERINCREMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookByPriceStream',
    full_name='BooksSvc.GetBookByPriceStream',
    index=3,
    containing_service=None,
    input_type=book__pb2._BOOKREQUEST,
    output_type=book__pb2._BOOKBYPRICEINCREMENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSSVC)

DESCRIPTOR.services_by_name['BooksSvc'] = _BOOKSSVC


_QUOTESSVC = _descriptor.ServiceDescriptor(
  name='QuotesSvc',
  full_name='QuotesSvc',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=524,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetQuoteSnapshot',
    full_name='QuotesSvc.GetQuoteSnapshot',
    index=0,
    containing_service=None,
    input_type=common__pb2._SECURITYSYMBOLORID,
    output_type=quote__pb2._QUOTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetQuoteStream',
    full_name='QuotesSvc.GetQuoteStream',
    index=1,
    containing_service=None,
    input_type=common__pb2._SECURITYSYMBOLORID,
    output_type=quote__pb2._QUOTEUPDATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUOTESSVC)

DESCRIPTOR.services_by_name['QuotesSvc'] = _QUOTESSVC


_REFERENCEDATASVC = _descriptor.ServiceDescriptor(
  name='ReferenceDataSvc',
  full_name='ReferenceDataSvc',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=677,
  serialized_end=801,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSecurities',
    full_name='ReferenceDataSvc.GetSecurities',
    index=0,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=security__pb2._SECURITIES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBrokers',
    full_name='ReferenceDataSvc.GetBrokers',
    index=1,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=broker__pb2._BROKERS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REFERENCEDATASVC)

DESCRIPTOR.services_by_name['ReferenceDataSvc'] = _REFERENCEDATASVC


_SUBSCRIPTIONSVC = _descriptor.ServiceDescriptor(
  name='SubscriptionSvc',
  full_name='SubscriptionSvc',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  serialized_start=803,
  serialized_end=892,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSubscriptionStatus',
    full_name='SubscriptionSvc.GetSubscriptionStatus',
    index=0,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=subscription__pb2._SUBSCRIPTIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUBSCRIPTIONSVC)

DESCRIPTOR.services_by_name['SubscriptionSvc'] = _SUBSCRIPTIONSVC


_TRADESSVC = _descriptor.ServiceDescriptor(
  name='TradesSvc',
  full_name='TradesSvc',
  file=DESCRIPTOR,
  index=5,
  serialized_options=None,
  serialized_start=895,
  serialized_end=1033,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTradesSnapshot',
    full_name='TradesSvc.GetTradesSnapshot',
    index=0,
    containing_service=None,
    input_type=trades__pb2._TRADESREQUEST,
    output_type=trades__pb2._TRADES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTradesStream',
    full_name='TradesSvc.GetTradesStream',
    index=1,
    containing_service=None,
    input_type=trades__pb2._TRADESREQUEST,
    output_type=trades__pb2._TRADE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADESSVC)

DESCRIPTOR.services_by_name['TradesSvc'] = _TRADESSVC

# @@protoc_insertion_point(module_scope)
